### ISSUE TITLE
Using a `build-figma-plugin.main.js` file throws an `Unexpected token 'export'` error when building

### ISSUE THREAD

**Issue by fwextensions** [yuanqing/create-figma-plugin#197]
I followed [the instructions](https://yuanqing.github.io/create-figma-plugin/recipes/#customizing-the-underlying-esbuild-configuration) for adding an esbuild config file and used the code described there, but running a build with a `build-figma-plugin.main.js` file logs this error:

```sh
error esbuild error
    Unexpected token 'export'
```

I believe that [this line](https://github.com/yuanqing/create-figma-plugin/blob/main/packages/build/src/utilities/build-bundles-async/build-bundles-async.ts#L57) is using `importFresh()` to import the config file.  But that seems to assume it's requiring a CJS module, so I don't see how that could import an exported ES module.  If it's assuming CJS, then the build error makes sense.

**Comment by yuanqing** [comment]
Thanks for this. Can confirm that this is a bug / change in behavior caused by the latest version of `esbuild`. (The `@create-figma-plugin/build` package has tests to verify that both `export default` and `module.exports` syntax both work out-of-the-box.)

Am considering pinning certain dependencies to exact versions… 🤔
