### ISSUE TITLE
DropdownMenu source?

### ISSUE THREAD

**Issue by reintroducing** [yuanqing/create-figma-plugin#31]
Where is the source for DropdownMenu? I was trying to figure out if I can put a `label` in the options to live alongside `value` so that it can display something other than what is actually selected but I don't see the source anywhere in the repo. Is this component gone in the new version?

If so, I would also suggest that future development of a new release happens on a `next` branch which doesn't get merged until the new release is out of `alpha`/`beta`. Additionally, I noticed this repo doesn't have release notes or a changelog anywhere which makes it very hard to update and know what is being added/removed. Any chance for that?

**Comment by yuanqing** [comment]
> Where is the source for DropdownMenu? I was trying to figure out if I can put a label in the options to live alongside value so that it can display something other than what is actually selected but I don't see the source anywhere in the repo. Is this component gone in the new version?

I plan to revert the `DropdownMenu` component but there will likely be breaking API changes in the next version (`v1.0.0`). I had initially removed it when doing some large scale refactoring work because I thought that it was a bit of a half-baked UI

You can check the `v0.0.84` tag for the original source for `DropdownMenu`: https://github.com/yuanqing/create-figma-plugin/blob/v0.0.84/packages/ui/src/components/dropdown-menu/dropdown-menu.tsx

If you need to use this component right now and don’t want to have to deal with breaking changes later, I would recommend either rolling your own `DropdownMenu` component or perhaps copying/adapting the code I linked above to your own repository

> If so, I would also suggest that future development of a new release happens on a next branch which doesn't get merged until the new release is out of alpha/beta. Additionally, I noticed this repo doesn't have release notes or a changelog anywhere which makes it very hard to update and know what is being added/removed. Any chance for that?

You’re absolutely right. Development should have happened on a separate branch – I’ll make it a point to do that after I cut the next stable release

The entire repo has undergone significant development recently eg. addition of vastly improved types, sub-second compilation times using esbuild.

I plan to do a `v1.0.0` release soon (aiming for within the new couple of weeks) – it will not be a `v0.0.85`. You can expect all APIs across all modules to stabilize with effect from this `v1.0.0` release.

That said, it is in my plans to:

1. Limit the number of breaking changes as far as possible going from `v0.0.84` to `v1.0.0`
2. Start publishing a Changelog

**Comment by reintroducing** [comment]
@yuanqing Thanks for the explanation. I actually ended up using the TextAutocomplete as that UI is actually closer to what I was after (and I saw DropdownMenu was gone in the screenshot for the alpha). I would actually like to suggest the creation of a `Select` component which more closely mimics a select dropdown which is I think what you were after with DropdownMenu. My use case is really a `select` but one wasn't available. I'm trying to avoid having to re-create any UI elements myself but definitely could go down the route of custom components in the future if the need arises (it just didn't in this plugin because its relatively small so I wanted to use the UI out of the box).

As for the `v1.0.0` breaking release, you technically don't have any obligation to keep breaking changes out of the sub-1.x releases because according to semver, you can make breaking changes without doing a major release pre-1.x. That being said, I think you've made enough changes that I'd agree, a `v1.0.0` release would be the best way to go. 

Thank you for the roadmap outline of what is being planned. For your releases/changelogs, might I suggest https://intuit.github.io/auto/? We use it to publish our packages at work and its a tremendous tool that handles everything under the hood for you. You basically assign certain labels to your PRs and it'll take the PR titles and create a changelog/release notes based on them that is easy to digest. Each label is mapped to a release type, and it'll create the Github tags/releases for you automatically.

In any case, thank you for this tool, it has saved me time in developing this plugin and I certainly appreciate your work.

**Comment by reintroducing** [comment]
Also, i'm going to go ahead and close this as there is no real reason to keep it open.
