### ISSUE TITLE
Can't extend UI element styles

### ISSUE THREAD

**Issue by Fyzu** [yuanqing/create-figma-plugin#42]
I'm trying to extend styles of ui elements via `className` \ `class` props, but it doesn't work

Use case:
```js
import styles from './styles.css'

// ....

<Text class={styles.text}>Some Text</Text>
```

Possible solutions:
[Text Component](https://github.com/yuanqing/create-figma-plugin/blob/main/packages/ui/src/components/text/text.tsx)

```ts
// text.tsx

export function Text({
  align = 'left',
  bold = false,
  children,
  muted = false,
  numeric = false,
  class,
  className,
  ...rest
}: Props<HTMLDivElement, TextProps>): JSX.Element {
  return (
    <div
      {...rest}
      class={createClassName([
        class,
        className,
        styles.text,
        styles[align],
        bold === true ? styles.bold : null,
        muted === true ? styles.muted : null,
        numeric === true ? styles.numeric : null
      ])}
    >
      {children}
    </div>
  )
}
```

**Comment by yuanqing** [comment]
Passing in a `class` or `className` prop is not supported across all components at this time.

- For layout, what I’ve usually done is to wrap the components in a `div` and adding layout styles to that `div`.
- And if I need something more custom, I’d usually just write my own component from scratch in my plugin code.

Can you share you specific use case? Which specific component do you wish to extend the styles of?

**Comment by Fyzu** [comment]
It's common practice for all ui-kits to add additional styles.
Also a large number of wrappers, it's much worse and more difficult than just passing the style and overriding what you need.

Example:
I want to use a `Text Component`, but give it padding and positioning. In some cases, only change the line height.
There are a lot of such cases for other components too.

[Example from popular ui-kits](https://github.com/mui-org/material-ui/blob/next/packages/material-ui/src/Typography/Typography.js#L131)

**Comment by Fyzu** [comment]
@yuanqing any updates?

**Comment by yuanqing** [comment]
I’m following a different philosphy with this UI library. [Braid](https://seek-oss.github.io/braid-design-system/) is an example of a UI library that doesn’t allow components to take a `className` prop. Each component can only be customized via a strict prop API.

For layout, you can either use [Layout components](https://github.com/yuanqing/create-figma-plugin/tree/78d944331293b0442bf87c41161ec026425e9b70/packages/ui/src/components/layout) or use wrapper `div`s with your own custom layout styles.

For low-level style customizations, my recommendation is to make a local copy of the component you want to customize in your plugin itself. This library is not meant for low-level style customizations because the intention is to follow the Figma editor’s UI design as closely as possible.

**Comment by combdn** [comment]
@Fyzu, the best workaround I’ve found so far is inline styles. You still get updates but get enough control for small (and not-so-small) tweaks.
