### ISSUE TITLE
Manifest documentation and blueprint deprecated

### ISSUE THREAD

**Issue by Pi0up** [yuanqing/create-figma-plugin#55]
Hi,

The doc and the blueprint available here:
[https://github.com/yuanqing/create-figma-plugin/blob/main/docs/recipes/multiple-commands.md](https://github.com/yuanqing/create-figma-plugin/blob/main/docs/recipes/multiple-commands.md)

are not matching official docs and behaviors:
[https://www.figma.com/plugin-docs/manifest/](https://www.figma.com/plugin-docs/manifest/)

separators in menu list must be specficied as :
`{"separator": true},`
not like
`"-",`

 and menu items for lauching UIs are not compliant
you have to specify launch IU in your command handler like in main.ts:
`
if(figma.command === 'myCommand')
  {
figma.showUI(html,options)
  }`
create-figma-plugin `showUI()` utility is not working in that case.
At this point, I don't know how I can have one UI by command using create-figma-plugin.

**Comment by yuanqing** [comment]
:wave: Thanks for your interest in this toolkit!

1. I recommend reading the official documentation: https://yuanqing.github.io/create-figma-plugin/

2. See https://yuanqing.github.io/create-figma-plugin/#configuration for the configuration API to be used in your `package.json` – there are various intentional differences with Figma’s `manifest.json` API. The `manifest.json` for your plugin will be generated on demand by the `build-figma-plugin` CLI.

3. See https://yuanqing.github.io/create-figma-plugin/#ui-1 for instructions for how to add a UI to your plugin command.

4. See https://github.com/yuanqing/awesome-create-figma-plugin#open-source-plugins for various examples of open source plugins built with Create Figma Plugin, many of which have a UI.

Hope this helps! Otherwise, this is a list of other boilerplates/tools that you may want to consider using instead of Create Figma Plugin: https://github.com/thomas-lowry/figma-plugins-on-github#resources
