### ISSUE TITLE
Resizer component

### ISSUE THREAD

**Issue by saeedalipoor** [yuanqing/create-figma-plugin#59]
Hi @yuanqing 
I'm trying to add a resizer component to the ui package of `create-figma-plugin`. It needs to add an event listener to the plugin core. what's your opinion about this utility function?
I'm thinking about adding a utility function that fires `figma.ui.resize` on resize, something like this.

```js
/* ui.tsx */
<UI>
...
<Resizer
	onResize={size=>emit('RESIZE', size)}
	default={{width, height}}
	min={{width, height}}
	max={{width, height}}
/>
</UI>
```

```js
/* main.ts */
import {resizeListener} from 'utilities';
resizeListener();
```

![2021-09-18 15 58 09](https://user-images.githubusercontent.com/1343083/133887250-72958f8f-f531-4fb9-8ee8-16738f302b93.gif)

**Comment by yuanqing** [comment]
@saeedalipoor Thanks for this suggestion and your work on this! I think this would be an extremely valuable addition to the library :+1:

# API

I think the API should be a **hook** called `useWindowResize` rather than a component. In my mind, the function signature of `useWindowResize` should be something like:

```ts
// packages/ui/src/hooks/use-window-resize.ts

export function useWindowResize (
  onResize: (size: { width: number; height: number }) => void,
  options?: {
    maxHeight: number,
    maxWidth: number,
    minHeight: number,
    minWidth: number
  }
) : void {
  // ...
}
```

- `options` is optional. If `options` is not specified, then:
  - `minWidth` and `minHeight` should default to the smallest plugin window size allowed by Figma. (IIRC the smallest possible `width` is `240`. Need to look up the docs on what the smallest `height` is.)
  - `maxHeight` and `maxWidth` should be `undefined` ie. the window resizing will be unconstrained.
- I don’t think a `default` size is needed because the initial window size would have been specified in the call to `showUI`.

# Usage

This would be how the `useWindowResize` hook can be used together with the `on` and `emit` utilities:

```tsx
// ui.tsx

import { useWindowResize } from '@create-figma-plugin/ui'
import { emit } from '@create-figma-plugin/utilities'

export default function () {
  // ...
  useWindowResize(
    function (size: { width: number; height: number }): void {
      emit('SET_WINDOW_SIZE', size)
    }
  )
}
```

```ts
// main.ts
import { on } from '@create-figma-plugin/utilities'

export default function () {
  // ...
  on(
    'SET_WINDOW_SIZE',
    function (size: { width: number; height: number }): void {
      window.resizeTo(size.width, size.height)
    }
  )
}
```

Preference is to keep things explicit rather than adding a `resizeListener` utility, which feels like a bit too much “magic”, IMO.

What do you think? Happy to discuss further and figure out how we can get this feature merged in

**Comment by saeedalipoor** [comment]
@yuanqing Thanks for clarifying that, I got the points.
I chose the component to have a handle to resize the window but It can also be returned through Hook, and it's better 👍
I Will open a PR next few days.

I have this idea about default size that I implemented in one of my plugins.
|![default size use case](https://user-images.githubusercontent.com/1343083/133927948-bf8fa4f3-34ea-46c6-88fb-6b2041dab8a0.gif)|
|:--:|
| default size use case for allowing to reset window size on double click |

I think that would be great if there is a template to choose when initiating a plugin to have a resizable UI.

**Comment by yuanqing** [comment]
To make this hook more useful, I think the hook should return a plain object (rather than `void` as I’d previously suggested):

```
const {
  setWindowSize,
  size
} = useWindowSize(
  function (size: { width: number; height: number }): void {
    emit('SET_WINDOW_SIZE', size)
  }
)
```

- `setWindowSize` is a function with the signature `(size: { width: number; height: number }) => void` – essentially this is a way to trigger the resize callback imperatively. For your use case, you could call `setWindowSize(defaultSize)` in your double-click handler to achieve the UX you’re after.
- On further consideration, I think the name `useWindowSize` for the hook might be better.

So the signature of the `useWindowSize` hook might be something like:

```
// packages/ui/src/hooks/use-window-resize.ts

export function useWindowSize (
  onWindowResize: (size: { width: number; height: number }) => void,
  options?: {
    maxHeight: number,
    maxWidth: number,
    minHeight: number,
    minWidth: number
  }
) : {
  setWindowSize: (size: { width: number; height: number }) => void,
  size: { width: number; height: number }
} {
  // ...
}
```

**Comment by saeedalipoor** [comment]
I expected that the hook should return a `getResizerProps` function. (with some pointer event listeners).
Could you clarify this for me?

```js
const {
	setWindowSize,
	size,
	getResizerProps
} = useWindowSize()

return(
	<Fragment>
		// ...
		<div {...getResizerProps()} />
	</Fragment>
)
```

**Comment by yuanqing** [comment]
Can we create a `div` within a `useEffect` hook within the `useWindowSize` hook?

```ts
// packages/ui/src/hooks/use-window-size.ts

useEffect(function () {
  // Create and append a `div` to `document.body`
  // ...

  // Position the `div` at the bottom-right corner
  // ...

  // Bind pointer event listeners on the `div` and call the `onWindowResize` callback as needed
  // ...

  return function () {
    // Remove the `div` from `document.body`
    // ...

  }
}, [onWindowResize])
```

**Comment by saeedalipoor** [comment]
Of course! I hadn't considered it.

**Comment by Jeremy-Knudsen** [comment]
I was making one of these too ... I think I will sit back and let you two hash this out! It's looking great!!!

**Comment by broisnischal** [comment]
how can i add the editor?
