### ISSUE TITLE
Support build for ReactJS

### ISSUE THREAD

**Issue by anhbinhvodanh** [yuanqing/create-figma-plugin#73]
Thank for a good library.
At the moment, I am working on a project and need to use this libary https://github.com/pmndrs/react-three-fiber but it doen't support for Preact. https://github.com/preactjs/preact/issues/2538
So, I deciced that I will not use the ui package but still want to use the build package for the compilation. 

I already patched some workaround code to support build ReactJS https://github.com/anhbinhvodanh/klara-figma-plugin/commit/74d85134c8f54db188c485418463cce9ef7bd6f2

Thanks.

**Comment by yuanqing** [comment]
@anhbinhvodanh 

1. Instead of patching `build-bundles-async.js`, you can modify the esbuild configuration via a `./build-figma-plugin.ui.js` file. Refer to the [recipe](https://yuanqing.github.io/create-figma-plugin/#customizing-the-underlying-esbuild-configuration).
2. Instead of patching `@create-figma-plugin/tsconfig/tsconfig.json`, I’d recommend just writing your own `tsconfig.json` from scratch.

**Comment by anhbinhvodanh** [comment]
Thank for your information.
